---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: wasm-test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  wasm:
    - name: wasm-filter
      rootID: root_id
      code:
        type: HTTP
        http:
          url: https://raw.githubusercontent.com/akhenakh/wasm-filter-go/main/build/plugin.wasm
          sha256: 8ac73efb3ee6808ac92aa47f4f9c897e7a547003b2b18d56404f5239dcc2542b

